//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LameSpy.rc
//
#define IDS_APP_TITLE                   102
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_LAMESPY                     109
#define IDC_TOOLBAR                     110
#define IDI_LAMESPY                     129
#define IDR_CONTEXT_SERVER              130
#define IDI_GAME_Q3                     156
#define IDI_GAME_QW                     157
#define IDI_GAME_UT99                   158
#define IDI_GAME_Q2                     159
#define IDI_GAME_UG                     160
#define IDI_GAME_DX                     161
#define IDB_GREENGUY                    179
#define IDB_REFRESHSERVER               197
#define IDB_REFRESHLIST                 198
#define IDB_SETTINGS                    199
#define IDB_ADDSERVER                   200
#define IDB_REMOVESERVER                201
#define IDB_PHONE                       202
#define IDB_SERVERINFO                  203
#define IDB_JOYSTICK                    204
#define IDB_STARTGAME                   205
#define IDB_REFRESHGLOBE                206
#define IDD_SETTINGS                    207
#define IDD_ABOUT                       208
#define IDR_SOUND_ABORT                 209
#define IDR_SOUND_ALERT                 210
#define IDR_SOUND_COMPLETE              211
#define IDR_SOUND_LAUNCH                212
#define IDR_SOUND_WELCOME               213
#define IDD_ADDFAVORITE                 214
#define IDB_LAMESPY                     215
#define IDD_BUDDYLIST                   216
#define IDD_CHATWINDOW                  217
#define IDD_GAMECONFIG                  218
#define IDD_FILTERS                     219
#define IDD_PROFILE                     220
#define IDD_GAMETOGGLE                  221
#define IDB_PNG1                        223
#define IDB_LAMEGUY1                    223
#define IDC_TREE_GAMES                  500
#define IDC_LIST_SERVERS                501
#define IDC_LIST_PLAYERS                502
#define IDC_LIST_RULES                  503
#define IDC_BUDDYTREE                   504
#define IDC_CHAT_LOG                    505
#define IDC_ABOUTTEXT                   1045
#define IDC_ABOUTTEXT2                  1046
#define IDC_CHECK_SHOWMASTERS           1047
#define IDC_CHECK_AUTOFETCH             1048
#define IDC_EDIT_PORT                   1051
#define IDC_FAVORITE_SELECTGAME         1052
#define IDC_COMBO1                      1054
#define IDC_IPADDRESS1                  1055
#define IDC_IP_INPUT                    1055
#define IDC_RADIO_DNS                   1060
#define IDC_RADIO_IP                    1061
#define IDC_EDIT1                       1062
#define IDC_GAMECONFIG_PATH             1062
#define IDC_NAMEINPUT                   1062
#define IDC_TREE1                       1063
#define IDC_GAMECONFIG_SELECT           1067
#define IDC_EDIT2                       1068
#define IDC_GAMECONFIG_CMD              1068
#define IDC_SEARCHEXE                   1069
#define IDC_GAMECONFIG                  1070
#define IDC_GAMECONFIG_FILE             1070
#define IDC_BUTTON1                     1071
#define IDC_UPDATE                      1071
#define IDC_CHAT_SEND                   1073
#define IDC_CHAT_INPUT                  1074
#define IDC_DNS_INPUT                   1075
#define IDC_SOUNDS_FRAME                1077
#define IDC_LIST_FRAME                  1078
#define IDC_SELECT_FRAME                1079
#define IDC_FILTERS_EMPTY               1080
#define IDC_FILTERS_FULL                1081
#define IDC_FILTERS_PASSWORD            1082
#define IDC_FILTERS_SEARCH              1084
#define IDC_FILTERS_FIELD               1085
#define IDC_GAMECONFIG_LABEL2           1086
#define IDC_GAMECONFIG_LABEL1           1087
#define IDC_GAMECONFIG_SAVE             1088
#define IDC_EXPANDONSTART               1089
#define IDC_SHOWQTV                     1090
#define IDC_HIDEDEADINTERNETS           1091
#define IDC_TEXTSIZE_RIGHT              1092
#define IDC_TEXTSIZE_LEFT               1093
#define IDC_SOUND_WELCOME               1095
#define IDC_LIST1                       1095
#define IDC_SOUND_COMPLETE              1096
#define IDC_SOUND_ABORTED               1097
#define IDC_SOUND_KILLING               1098
#define IDC_CHECK_DEDUPE                1099
#define IDC_CHECK_FAVESFILTER           1100
#define IDC_FAVORITEGAME                1101
#define IDC_ABOUT_IMAGE                 1102
#define IDC_LAMELINK                    1102
#define ID_SERVER_CONNECT               4001
#define ID_SERVER_COPYIP                4002
#define ID_SERVER_REFRESH_SINGLE        4003
#define ID_SERVER_INFO                  4004
#define ID_SERVER_CREATE_SHORTCUT       4005
#define ID_FAVORITES_ADD                32808
#define ID_FAVORITES_REMOVE             32809
#define ID_SERVER_REFRESH               32810
#define ID_SERVER_REFRESHSERVER         32811
#define ID_SERVER_FETCHNEWLIST          32812
#define ID_SERVER_DUMPMASTER            32813
#define ID_SERVER_CLEARCACHE            32814
#define ID_LAMESPY_SETTINGS             32816
#define ID_LAMESPY_ABOUT                32817
#define ID_SERVER_SERVERINFO            32818
#define ID_LAMESPY_CHAT                 32819
#define ID_LAMESPY_PROFILE              32820
#define ID_INFO_ABOUT                   32821
#define ID_LAMESPY_GAMESETUP            32822
#define ID_SERVERS_CANCELQUERIES        32823
#define ID_SERVERS_FILTERS              32824
#define ID_HELP_TUTORIALS               32825
#define ID_HELP_LAMESPY                 32826
#define ID_HELP_DISCORD                 32827
#define IDC_STATIC                      -1
#define IDC_SETTINGS_SOUNDS             -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
